QUOTES = [
    "That which does not kill us makes us stronger.",
    "He who fights with monsters might take care lest he thereby become a monster. And if you gaze for long into an abyss, the abyss gazes also into you.",
    "Without music, life would be a mistake.",
    "There are no facts, only interpretations.",
    "The man of knowledge must be able not only to love his enemies but also to hate his friends.",
    "We should consider every day lost on which we have not danced at least once.",
    "Man is the cruelest animal.",
    "Is man merely a mistake of God's? Or God merely a mistake of man?",
    "The thought of suicide is a great consolation: by means of it one gets through many a dark night.",
    "Be careful, lest in casting out your demon you exorcise the best thing in you.",
    "A good writer possesses not only his own spirit but also the spirit of his friends.",
    "Art is the proper task of life.",
    "What does your conscience say? — 'You should become the person you are'.",
    "The pure soul is a pure lie.",
    "That for which we find words is something already dead in our hearts",
    "I have forgotten my umbrella.",
    "God is dead! God remains dead! And we have killed him.",
    "Which is it: is man one of God's blunders, or is God one of man's blunders?"
]
